### ISSUE TITLE
sorry it me again, i cant in the board

### ISSUE THREAD

**Issue by metalbug** [hexator/live4chan#12]
this tells me "Board doesn't exist :("
what can i do?
I'm sorry I need your help.

**Comment by hexator** [comment]
Which board are you trying to visit?  Say it's /v. The URL should be: http://yoursite.com/chat/v

Board doesn't exist comes up if the board isn't in the list of boards you configured.

**Comment by metalbug** [comment]
yes, the URL is http://192.168.1.198:5080/chat/v
this need nginx proxy? and domain name?
i do not have to modify any settings,

A list of the top left of options to choose from, but which shows the

home
/undefined - (undefined)
/undefined - (undefined)
/undefined - (undefined)
/undefined - (undefined)
/undefined - (undefined)
/undefined - (undefined)

can in the undefined
but of course 
"This board does not exist."

**Comment by metalbug** [comment]
I used VMware and ubuntu 15.10 server

sudo apt-get install -y git mongodb imagemagick libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ ffmpeg

wget http://nodejs.org/dist/latest-v0.10.x/node-v0.10.42.tar.gz
tar zxvf node-v0.10.42.tar.gz
cd node-v0.10.42
./configure && make
sudo make install

curl -O -L https://npmjs.org/install.sh
sudo sh install.sh

git clone https://github.com/hexator/live4chan.git -b testing
cd live4chan; npm install

wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz; gunzip GeoLiteCity.dat.gz
git checkout node_modules/captcha/captcha.js
cd ..; git clone https://github.com/emgram769/ircd.js; cd live4chan
cp config.js.sample config.js
mkdir public/tmp/uploads
mkdir public/tmp/thumb
chmod 777 public/tmp/uploads public/tmp/thumb

node lib/set-password.js

$node -v
v0.10.42
$npm -v
3.7.2

npm start

I did not see any errors, help me please!

**Comment by hexator** [comment]
As I mentioned, the "testing" branch has a modified config file.  You need to make sure you do this step from the new readme.md

12) Copy the config.js.sample file to config.js and edit the configuration

cp config.js.sample config.js

**Comment by metalbug** [comment]
yes i follow the readme.md step by step, do it again and again
of course i cp config.js.sample to config.js
but there is nothing to be modified.

**Comment by hexator** [comment]
Hmm.  OK, the board list is retrieved using a websocket connection.  Do you have javascript turned off in your browser or anything like uMatrix running?

Also can you post any of the npm console output?  Mainly those sections that might show an error.  You might want to look in the javascript console of your browser for any client side errors as well.  If you see them, please post them and I'll take a look and see if I can help.

**Comment by metalbug** [comment]
[15:04:37.244] Error: The connection to ws://192.168.1.198:5080/socket.io/1/websocket/-sxtLPFAiXJSr4LkMXpS was interrupted while the page was loading. @ http://192.168.1.198:5080/socket.io/socket.io.js:2371
[15:04:38.486] GET http://192.168.1.198:5080/chat/int [HTTP/1.1 304 Not Modified 29ms]
[15:04:37.288] [object Object] @ http://192.168.1.198:5080/js/main_common.js:157
[15:04:37.289] false @ http://192.168.1.198:5080/js/chat.js:807
[15:04:38.881] GET http://192.168.1.198:5080/socket.io/1/?t=1455779078520 [HTTP/1.1 200 OK 18ms]

**Comment by metalbug** [comment]
can you send me the source code of livebunker.rocks?
i just want make like livebunker website

**Comment by hexator** [comment]
You have the source code.  It's running exactly what's posted here in the "testing" branch.

So, from the error message the websocket connection is dropping.  That might be this firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=712329

Try a different browser other than a FireFox variant and see what happens.

**Comment by hexator** [comment]
Also, I've added a bug to the project to work around the Firefox issue in case that's the problem.

**Comment by metalbug** [comment]
Yeah, I tried the other browsers, all the same.

The connection to ws://192.168.1.144:5080/socket.io/1/websocket/HbRVWcW7MXmyLmYuYHw8 was interrupted while the page was loading. socket.io.js:2371:21
Object { count: 0, convo: "", body: "You have been disconnected from the…", name: "", date: "Fri Feb 19 2016 11:30:56 GMT+0800", trip: "Status" } main_common.js:157:5
false chat.js:807:1

**Comment by metalbug** [comment]
root@ubuntu:~/live4chan# npm start

> LiveChan@0.0.1 start /root/live4chan
> node lib/index.js

Missing certificate or private key
Running with insecure server
   info  - socket.io started
connect.limit() will be removed in connect 3.0
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server (insecure) listening on port 5080 in development mode

Is it possible to development mode of the problem?

**Comment by hexator** [comment]
OK, I think I had a stale config.js.sample in the repository.

Do a "git pull" to get the new config.js.sample, copy that over to config.js, and see how it works for you.

**Comment by metalbug** [comment]
yea! finally succeeded, it works, it good, thanks man, thank you very much

**Comment by hexator** [comment]
Glad it worked!
